import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import * as local from '../src/local.mjs';

const MUSIC = '/tmp/claude-0/music';
test('scan, metadata, art, lyrics', { skip: !fs.existsSync(MUSIC) }, async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ml-'));
  local.init(dir);
  local.addFolder(MUSIC);
  const tracks = await local.scan();
  assert.ok(tracks.length >= 3);
  const n = tracks.length;
  const first = tracks.find((t) => t.title === 'First Song');
  assert.deepEqual(first.artists.map((a) => a.name), ['Test Artist', 'Guest']);
  assert.equal(first.album.name, 'Album One');
  assert.ok(first.duration >= 29 && first.duration <= 31, String(first.duration));
  assert.match(first.id, /^lc_[0-9a-f]{16}$/);
  const second = tracks.find((t) => t.title === 'Second Song');
  assert.equal(second.loudnessDb, 6.5);
  const loose = tracks.find((t) => t.title === 'Untagged Tune');
  assert.deepEqual(loose.artists.map((a) => a.name), ['Someone']);
  const art = await local.artwork(first.id);
  assert.ok(art && art.data.length > 50 && /image\//.test(art.mime));
  const art2 = await local.artwork(loose.id);
  assert.ok(art2 && art2.mime === 'image/png');
  const ly = await local.lyrics(second.id);
  assert.match(ly.synced, /Hello local/);
  assert.equal(local.pathFor(first.id), path.join(MUSIC, 'Album One/01 First Song.mp3'));
  local.flush();
  local.init(dir);
  assert.equal(local.tracks().length, n);
  local.removeFolder(MUSIC);
  assert.equal(local.tracks().length, 0);
  const opened = await local.openFiles([path.join(MUSIC, 'loose')]);
  assert.equal(opened.length, 1);
  assert.equal(local.tracks().length, 1);
});
