// Soncle · by minuda2009 (https://github.com/minuda2009) · GPL-3.0-or-later
// Generated from fixtures/store/defaults.json (which comes from src/defaults.mjs).
// Do not edit by hand: run tools/fixtures/export-store.mjs then tools/fixtures/gen-defaults.mjs.
namespace Soncle.Core.Store;

internal static class DefaultsData
{
    internal const string Json = """{"defaultSettings":{"volume":0.8,"dynamicColor":true,"accent":"#bfc2f0","theme":"dark","mica":true,"quality":"best","autoplay":true,"normalize":true,"lang":"en","location":"US","crossfade":0,"crossfadeGapless":true,"crossfadeOnSkip":false,"skipSilence":false,"silenceInstant":false,"tempo":1,"varispeed":false,"persistentQueue":true,"rememberShuffleRepeat":true,"noDuplicates":false,"autoSkipOnError":true,"sleepFadeOut":true,"sleepDefault":30,"closeToTray":false,"discord":false,"syncLikes":true,"autoDownloadLiked":false,"perDeviceSound":true,"autoDeviceEq":true,"pauseOnDisconnect":true,"btLyricsDelay":200,"outputDevice":"default","mono":false,"balance":0,"flowRadio":true,"flowLearn":true,"flowXf":true,"motionStyle":"classic","noticeSeen":false,"welcomed":false,"smartDuck":"duck","duckLevel":0.25,"focusMinutes":50,"focusPauseAtEnd":false,"focusBackup":null,"xfCurve":"smooth","xfStyle":"smart","gapless":true,"normTarget":-14,"headphone":null,"headphoneOn":true,"smartCrossfade":true,"autoHeadroom":true,"loudnessComp":false,"stereoWidth":1,"crossfeed":"off","lyricsSize":30,"lyricsAlign":"left","lyricsAutoScroll":true,"lyricsGlow":true,"squiggly":true,"density":"comfortable","eq":{"enabled":false,"preset":"Flat","preamp":0,"gains":[0,0,0,0,0,0,0,0,0,0]}},"defaults":{"liked":[],"playlists":[],"savedAlbums":[],"savedPlaylists":[],"followedArtists":[],"history":[],"searchHistory":[],"downloads":{},"settings":{"volume":0.8,"dynamicColor":true,"accent":"#bfc2f0","theme":"dark","mica":true,"quality":"best","autoplay":true,"normalize":true,"lang":"en","location":"US","crossfade":0,"crossfadeGapless":true,"crossfadeOnSkip":false,"skipSilence":false,"silenceInstant":false,"tempo":1,"varispeed":false,"persistentQueue":true,"rememberShuffleRepeat":true,"noDuplicates":false,"autoSkipOnError":true,"sleepFadeOut":true,"sleepDefault":30,"closeToTray":false,"discord":false,"syncLikes":true,"autoDownloadLiked":false,"perDeviceSound":true,"autoDeviceEq":true,"pauseOnDisconnect":true,"btLyricsDelay":200,"outputDevice":"default","mono":false,"balance":0,"flowRadio":true,"flowLearn":true,"flowXf":true,"motionStyle":"classic","noticeSeen":false,"welcomed":false,"smartDuck":"duck","duckLevel":0.25,"focusMinutes":50,"focusPauseAtEnd":false,"focusBackup":null,"xfCurve":"smooth","xfStyle":"smart","gapless":true,"normTarget":-14,"headphone":null,"headphoneOn":true,"smartCrossfade":true,"autoHeadroom":true,"loudnessComp":false,"stereoWidth":1,"crossfeed":"off","lyricsSize":30,"lyricsAlign":"left","lyricsAutoScroll":true,"lyricsGlow":true,"squiggly":true,"density":"comfortable","eq":{"enabled":false,"preset":"Flat","preamp":0,"gains":[0,0,0,0,0,0,0,0,0,0]}},"cookie":"","session":null,"lyricsOffsets":{},"eqPresets":[],"deviceProfiles":{},"skips":{}}}""";
}
