const { contextBridge, ipcRenderer, webUtils } = require('electron');

const call = async (ch, ...args) => {
  const r = await ipcRenderer.invoke(ch, ...args);
  if (!r.ok) throw new Error(r.error);
  return r.data;
};

contextBridge.exposeInMainWorld('api', {
  platform: process.platform,
  home: (chip) => call('yt:home', chip),
  homeMore: () => call('yt:homeMore'),
  explore: () => call('yt:explore'),
  browse: (id, params) => call('yt:browse', id, params),
  suggestions: (q) => call('yt:suggestions', q),
  search: (q, type) => call('yt:search', q, type),
  searchMore: (q, type) => call('yt:searchMore', q, type),
  album: (id) => call('yt:album', id),
  artist: (id) => call('yt:artist', id),
  playlist: (id, all) => call('yt:playlist', id, all),
  upNext: (id, pl) => call('yt:upNext', id, pl),
  radio: (pl, params) => call('yt:radio', pl, params),
  related: (id) => call('yt:related', id),
  library: () => call('yt:library'),
  songInfo: (id) => call('yt:songInfo', id),
  rate: (id, like) => call('yt:rate', id, like),
  prefetch: (id) => call('yt:prefetch', id),
  lyrics: (t) => call('lyrics', t),
  signIn: () => call('auth:signIn'),
  signInBrowser: () => call('auth:browser'),
  signOut: () => call('auth:signOut'),
  authStatus: () => call('auth:status'),
  premiumStatus: () => call('auth:premium'),
  storeGet: () => call('store:get'),
  storeSet: (k, v) => call('store:set', k, v),
  download: (tracks) => call('dl:add', tracks),
  removeDownload: (id) => call('dl:remove', id),
  downloads: () => call('dl:list'),
  downloadsSize: () => call('dl:size'),
  openDownloads: () => call('dl:openFolder'),
  btDevices: () => call('audio:bt'),
  setMini: (on) => call('win:mini', on),
  backup: () => call('app:backup'),
  restore: () => call('app:restore'),
  clearCache: () => call('app:clearCache'),
  openExternal: (u) => call('app:openExternal', u),
  info: () => call('app:info'),
  licences: () => call('app:licences'),
  hpSearch: (q) => call('eq:hpSearch', q),
  hpMatch: (model) => call('eq:hpMatch', model),
  hpProfile: (p) => call('eq:hpProfile', p),
  flowGet: (ids) => call('flow:get', ids),
  flowPut: (id, f) => call('flow:put', id, f),
  flowCount: () => call('flow:count'),
  flowClear: () => call('flow:clear'),
  power: () => call('sys:power'),
  localFolders: () => call('local:folders'),
  localAddFolder: () => call('local:addFolder'),
  localRemoveFolder: (dir) => call('local:removeFolder', dir),
  localScan: () => call('local:scan'),
  localTracks: () => call('local:tracks'),
  localOpen: (paths) => call('local:open', paths),
  localPending: () => call('local:pending'),
  localReveal: (id) => call('local:reveal', id),
  pathForFile: (f) => { try { return webUtils.getPathForFile(f); } catch { return ''; } },
  onLocalProgress: (fn) => ipcRenderer.on('local:progress', (_e, p) => fn(p)),
  onLocalPlay: (fn) => ipcRenderer.on('local:play', (_e, t) => fn(t)),
  importSpotify: (link) => call('import:spotify', link),
  importParse: (text, name) => call('import:parse', text, name),
  importFile: () => call('import:file'),
  importMatch: (tracks) => call('import:match', tracks),
  importCancel: () => call('import:cancel'),
  onImportProgress: (fn) => ipcRenderer.on('import:progress', (_e, p) => fn(p)),
  sendState: (s) => ipcRenderer.send('player:state', s),
  saveSession: (s) => ipcRenderer.send('session:save', s),
  titlebarColor: (c) => ipcRenderer.send('titlebar:color', c),
  toggleFullscreen: () => ipcRenderer.send('win:fullscreen'),
  onMediaAction: (fn) => ipcRenderer.on('media-action', (_e, a) => fn(a)),
  onDownload: (fn) => ipcRenderer.on('dl:progress', (_e, p) => fn(p)),
  onWinState: (fn) => ipcRenderer.on('win:state', (_e, s) => fn(s)),
  onDuck: (fn) => ipcRenderer.on('duck', (_e, s) => fn(s))
});
